### ISSUE TITLE
Can't compile: error: no return statement in function returning non-void [-Werror=return-type]

### ISSUE THREAD

**Issue by acejacek** [bozimmerman/Zimodem#103]
Arduino IDE  throws back few errors like that in wificlientnode.ino, zcommand.ino and probably few others

**Comment by bozimmerman** [comment]
Wow -- no idea why I've never seen those errors, or why they haven't caused runtime crashes.  Weird, right?
Anyway, the fix in WiFiClientNode I could see, but the changes to zimodem.ino are useless because of .. I dunno, EOL changes?  It's just showing the entire file as changed. 

Any way, you can comment here with a local diff of that file, or some way that I can visually see the changes?

**Comment by acejacek** [comment]
That was super simple change, done directly in github.com. Added line 1871 with ‘return ZERROR’.” At the end of doHangupCommmand  No idea why diff looks so strange. Didn’t verify it prior, sorry. Maybe some collisions?BR/JacekOn 26 Mar 2023, at 09:36, Bo Zimmerman ***@***.***> wrote:﻿
Wow -- no idea why I've never seen those errors, or why they haven't caused runtime crashes.  Weird, right?
Anyway, the fix in WiFiClientNode I could see, but the changes to zimodem.ino are useless because of .. I dunno, EOL changes?  It's just showing the entire file as changed.
Any way, you can comment here with a local diff of that file, or some way that I can visually see the changes?
